---

- name: "Create the image storage irectory if it does not exist"
  ansible.builtin.file:
    path: {{ pi_image_dir }}
    state: directory
    mode: '0755'

- name: Download pi image
  get_url:
    url: "{{ pi_image_url}}/{{ pi_image_name }} "
    dest: "{{ pi_image_dir }}"
    mode: '0644'

- name: Unarchive pi image
  ansible.builtin.unarchive:
    src: "{{ pi_image_dir }}/{{ pi_image_name }}.zip"
    dest: /usr/local/bin
